### ISSUE TITLE
Installation broken on Ubuntu Xenial Xersus

### ISSUE THREAD

**Issue by ChaosCat** [HikariKnight/rsu-client#101]
I am running the following commands on Ubuntu 16.04 LTS and the installations seems to be broken, it is unable to find the JRE versions it depends on
This is the result of running 
`sudo apt update && sudo apt-get update && sudo apt-get install unix-runescape-client`:

``` console
Hit:1 http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease              
Hit:3 http://archive.canonical.com/ubuntu xenial InRelease                     
Hit:4 http://il.archive.ubuntu.com/ubuntu xenial InRelease                     
Hit:5 http://il.archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:6 http://il.archive.ubuntu.com/ubuntu xenial-backports InRelease [92.2 kB]
Get:7 https://content.runescape.com/downloads/ubuntu trusty InRelease [2,236 B]
Fetched 94.4 kB in 3s (27.7 kB/s)
Reading package lists... Done
W: https://content.runescape.com/downloads/ubuntu/dists/trusty/InRelease: Signature by key AAC9264309E4D717441DB9527373B12CE03BEB4B uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unix-runescape-client : Depends: openjdk-6-jre but it is not installable or
                                  openjdk-7-jre but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I tried manual installation of the packages but without success.
also seems to be that for some reason openjdk-7-jre [or 6] couldn't be found
result of running
`sudo apt install openjdk-7-jre openjdk-6-jre`:

``` console
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package openjdk-7-jre is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package openjdk-6-jre is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  icedtea-netx:i386 icedtea-netx-common icedtea-netx

E: Package 'openjdk-7-jre' has no installation candidate
E: Package 'openjdk-6-jre' has no installation candidate
```

**Comment by HostOnNet** [comment]
Ubuntu 16.04 have openjdk-8-jre, if you install rsu-client from github, then use this, it will work or wait for @HikariKnight to update package.

**Comment by ChaosCat** [comment]
@HostOnNet, I already jave the JREs set and working as you can see:

``` console
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

default-jre/xenial,now 2:1.8-56ubuntu2 amd64 [installed]
default-jre-headless/xenial,now 2:1.8-56ubuntu2 amd64 [installed,automatic]
openjdk-8-jre/xenial-updates,xenial-security,now 8u91-b14-0ubuntu4~16.04.1 amd64 [installed,automatic]
openjdk-8-jre-dcevm/xenial,now 8u74-1 amd64 [installed]
openjdk-8-jre-headless/xenial-updates,xenial-security,now 8u91-b14-0ubuntu4~16.04.1 amd64 [installed,automatic]
openjdk-8-jre-jamvm/xenial-updates,xenial-security,now 8u91-b14-0ubuntu4~16.04.1 amd64 [installed]
openjdk-8-jre-zero/xenial-updates,xenial-security,now 8u91-b14-0ubuntu4~16.04.1 amd64 [installed]
openjdk-9-jre/xenial,now 9~b114-0ubuntu1 amd64 [installed]
openjdk-9-jre-headless/xenial,now 9~b114-0ubuntu1 amd64 [installed,automatic]
```
I am afraid the problem lies within the package itself, I think @HikariKnight should update it to be able to use newer JREs as dependencies.
 I also downloaded installed the old JREs from oracle's site manually and compiled/installed them, however, the client still shows the same problem.

**Comment by HikariKnight** [comment]
Can't update this until I get internet at my new place, for now just install openjdk-8 packages and the runescape package and it will work

As the error is in the "Unix runescape client" package which just installs the runescape package, a sound layer(alsa or pulse) if you don't have one and java

**Comment by HikariKnight** [comment]
@ChaosCat @HostOnNet pushed update to the package as i now finally have internet again.
expect it to be available on launchpad.net in about 1 hour for manual download and maybe 1 hour 30 mins to 2 hours for install through apt-get

**Comment by rslinuxminthelp** [comment]
@HikariKnight @ChaosCat I just tried using the client using the commands for Linux mint and had the exact same problems as ChaosCat. Where should I go to get the updated version/how do I install it?

**Comment by DiurnalTeam** [comment]
@HikariKnight Brother , i'm diurnal  =) , can we talk about MUOnline , diurnalgaming@yahoo.com is my email me and Nocturnal was looking for your Arena PVP Map again but I think there was none posted in Ragezone, hope you could help us about this =)

**Comment by ChaosCat** [comment]
The launcher now installed and launches fine after a re-installation of the JDK (Included in one of the Ubuntu updates that I got recently it seems).

**Comment by HikariKnight** [comment]
@diurnalteam sorry I no longer have the files for it, but I do believe I have the map editing tools still.
Also noc has my Skype, he could just have messaged me

**Comment by Xizzid** [comment]
@HikariKnight i got the same problem as @ChaosCat is there any fixes out?

The following packages have unmet dependencies:
 unix-runescape-client : Depends: openjdk-6-jre but it is not installable or
                                  openjdk-7-jre but it is not installable

**Comment by HikariKnight** [comment]
@xizzid
The package should have been updated with openjdk-8-jre long ago.

Best solution would be to install the runescape package instead and use oracle java with it.

**Comment by jpptinsley** [comment]
I've got this one as well, on 16.04;
The following packages have unmet dependencies.
 unix-runescape-client : Depends: openjdk-6-jre but it is not installable or
                                  openjdk-7-jre but it is not installable

I can't install the official runescape package due to a bug there;
http://forum.runescape.com/forums.ws?415,416,69,65779981,goto,3

**Comment by HikariKnight** [comment]
@jpptinsley 
> - sudo apt-get install default-jre default-jre-headless runescape
