### ISSUE TITLE
Can't install on Debian

### ISSUE THREAD

**Issue by marndt93** [HikariKnight/rsu-client#102]
I'm trying to install the client on rasbian on my raspberry pi 3, not sure if ARM is supported but thought I'd try anyway.  Everything works fine until I input this line 'sudo apt-get update && sudo apt-get install unix-runescape-client'

I get this message: 

W: Failed to fetch http://launchpad.net/hikariknight/uix-runescape-client/ubuntu/dists/trusty/main/binary-armhf/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by HikariKnight** [comment]
you have misstyped the repository, you have written uix instead of unix
