### ISSUE TITLE
Client opens

### ISSUE THREAD

**Issue by Tick-Tech** [HikariKnight/rsu-client#103]
Client opens but when I click Play now it it does nothing. 
I'm using Fedora 23.

**Comment by HikariKnight** [comment]
run the command 

> runescape

and give us the output.

most likely youre missing java

**Comment by wtbtucker** [comment]
Do I need the most recent version of java? I'm having the same issue

**Comment by wtbtucker** [comment]
Here is my output when I hit play now
`Reading value from "prmfile"
Setting script data prmfile to oldschool.prm
WARNING: List::MoreUtils module not found on the system,
using the version provided by the client instead!

RuneScape Unix Client script version 4.3.5

The script is running from a system path!
/home/wtbtucker/.config/runescape will be used as client folder instead!

Symlinking icon and updating examples
cp: "/opt/runescape/share/configs/settings.conf.example" -> "/home/wtbtucker/.config/runescape/share/configs/settings.conf.example"
cp: "/opt/runescape/share/prms/runescape.prm.example" -> "/home/wtbtucker/.config/runescape/share/prms/runescape.prm.example"
Checking if any known files are still using the old folder structure

Checking if any default configurations are missing

Trying to read /home/wtbtucker/.config/runescape/share/configs/settings.conf
Reading value from "compabilitymode"
Setting script data compabilitymode to 0
Reading value from "preferredjava"
Setting script data preferredjava to default-java
Reading value from "forcepulseaudio"
Setting script data forcepulseaudio to 0
Reading value from "forcealsa"
Setting script data forcealsa to 0
Reading value from "useprimusrun"
Setting script data useprimusrun to false
Reading value from "optimizejava"
Setting script data optimizejava to true
Reading value from "cachedir"
Setting script data cachedir to default

Checking if any --verbose parameters were passed to the script
The --verbose parameter was not passed to the script.
Java will be executed without extra output.

Locating the binary that /usr/bin/java is symlinked to.
/usr/bin/java -> /etc/alternatives/java
/etc/alternatives/java -> /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java
Java binary located: /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java

Reading .prm file /home/wtbtucker/.config/runescape/share/prms/oldschool.prm
This is the info I gathered from the oldschool.prm file
######## File Start ########

######## File End ########

I will now parse the parameters!
Checking your client language setting(if any)
Trying to read file
/home/wtbtucker/jagexappletviewer.preferences

Unable to read jagexappletviewer.preferences file, defaulting to Language=0 (English).
I will now parse the contents from the
jagexappletviewer.preferences file so it can be used.
Stitching the language setting to the final parameters.

Final parameter string is:


Launching client using this java version: 
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (6b35-1.13.7-1ubuntu0.12.04.2)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

Fixing possible OpenGL issues by adding the environment variable
LD_LIBRARY_PATH=/opt/runescape/rsu/3rdParty/linux/cairo-nogl/i386/:/opt/runescape/rsu/3rdParty/linux/cairo-nogl/x86_64/:/usr/lib/jvm/java-6-openjdk-amd64/jre/bin/../lib/amd64/:/usr/lib/jvm/java-6-openjdk-amd64/jre/bin/../lib/amd64/jli/:$LD_LIBRARY_PATH

Adding optimization parameters to Java.
Parameters that will be added are:
-XX:+AggressiveOpts -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+TieredCompilation -XX:ReservedCodeCacheSize=256m -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=16 -XX:+UseParallelGC
NOTE: If any of these are added to the prm file the parameter from the prm file will be used instead!

Launching the RuneScape Client using this command:
cd /home/wtbtucker/.config/runescape/bin && LD_LIBRARY_PATH=/opt/runescape/rsu/3rdParty/linux/cairo-nogl/i386/:/opt/runescape/rsu/3rdParty/linux/cairo-nogl/x86_64/:/usr/lib/jvm/java-6-openjdk-amd64/jre/bin/../lib/amd64/:/usr/lib/jvm/java-6-openjdk-amd64/jre/bin/../lib/amd64/jli/:$LD_LIBRARY_PATH /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java -XX:+UseCompressedOops -XX:+AggressiveOpts -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+TieredCompilation -XX:ReservedCodeCacheSize=256m -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=16 -XX:+UseParallelGC -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Duser.home="/home/wtbtucker"   -cp   /share/img/OldSchool

Executing the RuneScape Client!
You are now in the hands of Jagex.

######## End Of Script ########
######## Jagex client output will appear below here ########

Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
    -jamvm        to select the "jamvm" VM
    -cacao        to select the "cacao" VM
    -zero         to select the "zero" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose[:class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -jre-no-restrict-search
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://java.sun.com/javase/reference for more details.
`

**Comment by HikariKnight** [comment]
Hmm that's odd it doesn't auto select  the  server  jvm. 

Try add
-server

To the misc settings in the  launcher (should be under the client settings tab)

**Comment by HikariKnight** [comment]
no reply in ages, closed
