### ISSUE TITLE
Installing rsu-client on linux Mint-Sarah

### ISSUE THREAD

**Issue by cootroot** [HikariKnight/rsu-client#104]
When i try to run the command to install the client i get this error message:

`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unix-runescape-client : Depends: openjdk-6-jre but it is not installable or
                                  openjdk-7-jre but it is not installable
E: Unable to correct problems, you have held broken packages.`

This is the whole console: 
`sudo apt-add-repository ppa:hikariknight/unix-runescape-client
[sudo] password for victor: 
You are about to add the following PPA:
##  NOTE: The packages in this PPA are built whenever the master branch on github is updated, plus it available for all architectures for testing and the rsu-launcher is optional(making it possible to support older ubuntu versions!)

This is the automatic PPA of the RuneScape Unix Client (RSU Client) which is a Perl port of the official RuneScape Windows Client/GameLauncher.
The aim of this project port is to replicate as much of the "jagexlauncher.exe" functionality while making it easier to add known fixes to the game on Linux. Like forcing sounds to play through pulseaudio or ALSA due to java not playing the in game sounds properly.
You can also use different java versions by editing the "preferredjava" setting inside ~/.config/runescape/share/settings.conf
along with several other settings.

For support please go to the wiki for known issues on linux.
http://services.runescape.com/m=rswiki/en/Linux_Known_Issues

Or go to the official Community - Linux thread to get support.
http://services.runescape.com/m=forum/forums.ws?25,26,99,61985129,goto,323
Please include as much detail as possible and also what fixes you have tried.
 More info: https://launchpad.net/~hikariknight/+archive/ubuntu/unix-runescape-client
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/tmp.0971xEsKxH/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv-keys
9BA73CFA
gpg: requesting key 9BA73CFA from hkp server keyserver.ubuntu.com
gpg: key 9BA73CFA: "Launchpad PPA for Hikari Knight" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
victor@cootroot ~ $ sudo apt-get update && sudo apt-get install unix-runescape-client
Get:1 https://content.runescape.com/downloads/ubuntu trusty InRelease [2,236 B]
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]  
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease  
Hit:4 http://repository.spotify.com stable InRelease  
Hit:5 http://archive.canonical.com/ubuntu xenial InRelease  
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]  
Hit:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease  
Ign:8 http://packages.linuxmint.com sarah InRelease  
Hit:9 http://packages.linuxmint.com sarah Release  
Hit:11 http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu trusty InRelease
Hit:12 http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu xenial InRelease
Fetched 192 kB in 35s (5,421 B/s)
Reading package lists... Done
W: https://content.runescape.com/downloads/ubuntu/dists/trusty/InRelease: Signature by key AAC9264309E4D717441DB9527373B12CE03BEB4B uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unix-runescape-client : Depends: openjdk-6-jre but it is not installable or
                                  openjdk-7-jre but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by Devices** [comment]
Same problem on Ubuntu 16.04 (obviously).

**Comment by HikariKnight** [comment]
pushed out a new package, please run

> sudo apt-get purge unix-runescape-client

before you install this .deb package or try to install again to remove any potential issues.

https://code.launchpad.net/~hikariknight/+archive/ubuntu/unix-runescape-client/+build/11051735
