### ISSUE TITLE
"Play OldSchool" button missing from launcher

### ISSUE THREAD

**Issue by msewell17** [HikariKnight/rsu-client#105]
@HikariKnight just finished installing on ubuntu-14.04, everything went perfectly, the client launcher loads up fine, but the "Play OldSchool" button isn't between "Play Now" and "Run Updater"
![missing_button](https://cloud.githubusercontent.com/assets/7648162/19616049/59aa854a-97b6-11e6-934a-9eea59ab8711.png)

**Comment by HikariKnight** [comment]
see the dropdown box with runescape.prm
click on it and select oldschool.prm and then click play

the selection is saved once you click play so it will remember your choice on the next launch

![image](https://cloud.githubusercontent.com/assets/2557889/19618716/f3dd070e-9852-11e6-9cdd-9c84088f00ce.png)
![image](https://cloud.githubusercontent.com/assets/2557889/19618718/082dc298-9853-11e6-98f1-0a18a63bfc58.png)

**Comment by msewell17** [comment]
Thanks I appreciate it
