### ISSUE TITLE
Notification: I have created builds for RSU Client for CentOS/RHEL/Scientific Linux 6, 7; Fedora 24, 25; openSUSE 13.2, 42.1, 42.2 and Tumbleweed using Open Build Service

### ISSUE THREAD

**Issue by fusion809** [HikariKnight/rsu-client#108]
Hi,

This client is the only RuneScape client I found works on Fedora, I have tried getting the RuneScape NXT Client to work but it doesn't work for me. So I have decided to do the RS-playing Linux community a service by building RPMs for RSU for the following Linux distributions in my OBS project:

* CentOS 6/7
* Fedora 24/25
* openSUSE 13.2/42.1/42.2/Tumbleweed
* Red Hat Enterprise Linux 6/7
* Scientific Linux 6/7

[Here](https://build.opensuse.org/package/show/home:fusion809/unix-runescape-client) is this package's page on my OBS project. To install it users merely need to click on "Download package" and follow the queues from there. I thought I could support CentOS 5 and RHEL 5 but I ended up having to drop it due to packaging issues. 

Thanks for your time,
Brenton

**Comment by HikariKnight** [comment]
Nice,  i will look at getting it added to main page if you give me the commands to add the repository and install the client

**Comment by fusion809** [comment]
It greatly depends on the distro in question, that's why I'd recommend directing them [here](https://software.opensuse.org/download.html?project=home%3Afusion809&package=unix-runescape-client) then they merely need to click on the logo of their distribution and follow the installation instructions provided.

**Comment by HikariKnight** [comment]
oh great thanks

**Comment by HikariKnight** [comment]
added to readme.md and credits
