### ISSUE TITLE
Elementary OS, OPENJDK-9 and RSU incompatability. OPENJDK-8 is fine.

### ISSUE THREAD

**Issue by jmfgdev** [HikariKnight/rsu-client#112]
Hey @HikariKnight I'm coming to you because I have never been so confused with Java or Linux. Ok so I installed RSU on Elementary OS with the debian method since apt-add-repository doesn't exist. I can't install the package unix-runescape-client since openjdk-7 doesn't exist, so I install runescape since it doesn't require openjdk-7 as a dependency. Once I get it installed I notice the fonts and performance is super glitchy. So i install openjdk-9-jre and matching headers package via Synaptic and then try again. OpenJDK 9 simply won't lauch so i remove openjdk-9-jre and matching headers package via Synaptic again and now when i type "java -version"  in a terminal window that was running since before I installed OpenJDK 9 i get, "bash: cd: /usr/bin/java: No such file or directory" but if I run the same command "java -version" in a new terminal I get:
"The program 'java' can be found in the following packages:
 * default-jre
 * gcj-5-jre-headless
 * openjdk-8-jre-headless
 * gcj-4.8-jre-headless
 * gcj-4.9-jre-headless
 * openjdk-9-jre-headless
Try: sudo apt install <selected package>"
default-jre and openjdk-8 packages are installed, so what happened to the link between the java command and java-8?

**Comment by jmfgdev** [comment]
Now when I try to lauch the actual game I get this in the console
"sh: 1: /usr/lib/jvm/java-9-openjdk-amd64/bin/java: not found"

**Comment by jmfgdev** [comment]
@HikariKnight I fixed this by using Synaptic to fully uninstall all my openjdk packages and reinstalled them, but the client still doesn't work with openjdk 9

**Comment by HikariKnight** [comment]
@jmfgdev thats odd as people have run it on openjdk-9 before

**Comment by jmfgdev** [comment]
It's likely just an issue on Elementary OS, like i said, the package unix-runescape-client will not install since openjdk-7 is not avail in the repos. removing openjdk-7 and openjdk-7 from the dependencies would let me install it but for now I can only install runescape and not the dummy URC package.
