### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Jonathan1223** [HikariKnight/rsu-client#116]
When I type on terminal "sudo add-apt-repository ppa:hikariknight/unix-runescape-client" says command not found. There is anyway to get it install runescape client on linux?

**Comment by ivanpu** [comment]
> `add-apt-repository`

That should be `apt-get-repository` ;)

**Comment by Jonathan1223** [comment]
I did that way and say the same thing

**Comment by ivanpu** [comment]
What distro are you using?
Is it Debian-based?

**Comment by Jonathan1223** [comment]
Mm I really dont understand, I did install linux with xfce and trusty

**Comment by ivanpu** [comment]
Trusty... that [should be](https://wiki.ubuntu.com/Releases) "Ubuntu 14.04".
The command should be present, but might not be installed.
Run `sudo apt-get install software-properties-common` to get that command, then you can continue installing this client.

**Comment by Jonathan1223** [comment]
It works! Thank you very much!

**Comment by ivanpu** [comment]
You welcome :)
