### ISSUE TITLE
Macos Can't install Addons

### ISSUE THREAD

**Issue by ibrokemypie** [HikariKnight/rsu-client#120]
@HikariKnight whenver you try to install an addon on macos sierra it seems to download, then pops up saying Copying Failed! Copying failed due to missing source location!
Please try again
This happens with every addon every time

**Comment by HikariKnight** [comment]
@ibrokemypie my macbook do not support macos sierra so i cant work on fixing that sadly as i do not have money to buy a new macbook just for that purpose.

I have aslo been considering to disable the addon functionality as they are a lot to solo maintain with my limited time. so sadly i cannot help with that :(
