### ISSUE TITLE
FreeBSD?

### ISSUE THREAD

**Issue by aimeec1995** [HikariKnight/rsu-client#122]
I read this has official support for FreeBSD. But, I see no package for it and I cannot seem to get it working under linux emulation due to perl. 
Help please?

**Comment by HikariKnight** [comment]
Well yes and no, the script has support for freebsd but dependencies like Java and jagex own libraries may or may not support freebsd

Let me find all the Perl dependencies for you. I can't remember if Java has to be run through Linux emulation or not but I'm not familiar with freebsd myself but I know people have made it run on freebsd and Solaris using my client scripts (idk if opengl worked or not though)

**Comment by HikariKnight** [comment]
Full list of dependencies 

Dependencies: 
default-jre 
default-jre-headless 
perl 
perl-modules 
p7zip-full 
wget|curl 
grep 
libwx-perl 
libconfig-inifiles-perl 
libmodule-extract-perl 
libio-stringy-perl 
libfile-copy-recursive-perl 
libhttp-tiny-perl 
libjson-perl 
libjson-pp-perl 
liblist-moreutils-perl 
liburi-encode-perl 
libxml-rsslite-perl 

Optional (for forcing sound on alsa or pulse) 
alsa-oss 
pulseaudio-utils

**Comment by aimeec1995** [comment]
Thanks

**Comment by HikariKnight** [comment]
youre welcome :)
