### ISSUE TITLE
Problems installing on Debian 9 Stretch

### ISSUE THREAD

**Issue by soaringowl2145** [HikariKnight/rsu-client#128]
Currently it depends on:

opendjk-6-jre
opendjk-7-jre

Debian says they are not installable and Stretch only has openjdk-8-jre in its repos.  Is there any way to update the app so that it can run off of openjdk-8-jre?

Thanks.

**Comment by soaringowl2145** [comment]
@HikariKnight

**Comment by ivanpu** [comment]
AFAIK, it works well with 8, but not sure right now how to force it on Debian...

**Comment by HikariKnight** [comment]
updated the debian install as i didnt know they had deprecated jre6 and 7

<pre>echo "deb http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu zesty main" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9BA73CFA
sudo apt-get update && sudo apt-get install unix-runescape-client</pre>

**Comment by HikariKnight** [comment]
just remember to remove your old entry for my ppa from your /etc/sources.list @soaringowl2145 

that old entry should be

deb http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu zesty main

**Comment by soaringowl2145** [comment]
@HikariKnight Thank you.  That fixed the issue, although the old repo was trusty not zesty.

Also you may want to specify that zesty is for Debian 9 and leave the old repo for Debian 8 for those that still use it.

**Comment by HikariKnight** [comment]
@soaringowl2145 nah the only difference between the 2 repos are that the unix-runescape-client package has jre 6-9 as dependency and if neither exists then it will go for default-jre :) and sadly launchpad pevents me from updating the trusty repo soon so the bump was needed :(

**Comment by soaringowl2145** [comment]
@HikariKnight Thanks.  So I think it is safe to close the issue now as it is working now.
