### ISSUE TITLE
[Question] When should I use the Client Updater?

### ISSUE THREAD

**Issue by soaringowl2145** [HikariKnight/rsu-client#129]
@HikariKnight 

I am wondering when I should use the updater and what it is used for.

Also it says I must be able to download the official client.  Does this mean I must have the official Runescape client repo setup?

Finally when the official Runescape client is updated will the RSU client be updated as well?

**Comment by HikariKnight** [comment]
no no the updater refers to the legacy client, you will only need to run it when jagex updates their jagexappletviewer.jar

it just has an option to download the windows or mac client and extract the jar from that or download the jar directly (as it has happened once in the past they have forgotten to update one of the downloads :P)

you will know when to update as you will usually get a black dialog box with black text (i know, amazing UX design there) which would tell you to update the client, it usually has 2 buttons, where one opens the download page for the official client. or it has a text field with a download link in, just ignore that message and open the updater instead in that case (as the link they provide you is usually for the mac or windows client)

**Comment by soaringowl2145** [comment]
Thanks for the quick response.  

When the official Runescape Legacy client is updated will the RSU client be updated as well?

**Comment by soaringowl2145** [comment]
@HikariKnight

**Comment by ivanpu** [comment]
> When the official Runescape Legacy client is updated will the RSU client be updated as well?

No, you only will need to update the .jar file (with the Updater). It's unrelated to this client updates.

**Comment by soaringowl2145** [comment]
Thanks.
