### ISSUE TITLE
How does one execute the client in the tar?

### ISSUE THREAD

**Issue by annadane** [HikariKnight/rsu-client#131]
Apologies in advance if simple technical questions don't belong in "issues" but I don't know where else to put it.

I downloaded the tar, and I tried "perl" /path/to/file and I get the following:

Can't locate Archive/Extract.pm in @INC (you may need to install the Archive::Extract module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/annadane/Runescape/rsu-client-master/runescape/rsu/rsu-query line 16.
BEGIN failed--compilation aborted at /home/annadane/Runescape/rsu-client-master/runescape/rsu/rsu-query line 16.

What's the correct way for launching the client?

**Comment by annadane** [comment]
Fixed it. I had to install the libarchive-extract-perl package.

**Comment by HikariKnight** [comment]
glad to hear you solved it, for some reason github has stopped sending me notifications about new issue tickets.
