### ISSUE TITLE
Ubuntu Artful RS3 Login Screen blank

### ISSUE THREAD

**Issue by RyoshiKayo** [HikariKnight/rsu-client#133]
Platform: Ubuntu Artful (17.10)
-Added with the PPA Package.

Installation works fine, the launcher works fine, and old school works fine, but when you launch the RS3 Client, it will load the background and the music but it will not present the login screen

![broken_rs3](https://user-images.githubusercontent.com/24500457/33237384-419874c4-d227-11e7-89eb-39dac5409852.png)

**Comment by RyoshiKayo** [comment]
I ran the launcher via the terminal to see if there were any specific errors and found the following:

```Error: client.init:1270 sun.reflect.NativeMethodAccessorImpl.invoke0 sun.reflect.NativeMethodAccessorImpl.invoke:62 sun.reflect.DelegatingMethodAccessorImpl.invoke:43 java.lang.reflect.Method.invoke:498 Rs2Applet.a:185 Rs2Applet.init:428 app.appletviewer.a:846 jagexappletviewer.main:34 | java.lang.RuntimeException | 
sun.awt.image.ImageFormatException: Unsupported color conversion request
	at sun.awt.image.JPEGImageDecoder.readImage(Native Method)
	at sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:141)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
Error: lr.ajk() im.i() | lr.ajk:11168 im.i:1128 xa.v:380 dx.z:273 z.o:228 pa.l:218 zx.em:1923 aja.n:576 aou.k:256 client.au:1515 rl.m:573 rl.s:549 rl.run:506 java.lang.Thread.run:748 | java.lang.ArrayIndexOutOfBoundsException: 0 | S 2693 3376 10431 10428 3451 2596 2595 2708 1172 336
```

**Comment by HikariKnight** [comment]
@RyoshiKayo from what i can tell of the output it seems like for some reason the client (jar) crashes with an Array Index Out Of Bounds exception so there is not really anything i can do with this myself as i have never seen the client crash with that exception before.

best bet would be send in a support ticket to jagex and include that last line (as the lines above are just complaining about the ingame cursor images) and tell them to forward it to some of the developers to ask for input, as the error is not from my scripts but from jagex own code, and then ofcourse just cross your fingers that something might happen.

Sorry for not being able to properly help with this :(

**Comment by RyoshiKayo** [comment]
@HikariKnight No problem, I'll make a ticket with them and update this thread on what I find out :)

**Comment by RyoshiKayo** [comment]
> I'm afraid while we do offer a Linux client, we don't strictly offer support for it.

**Comment by RyoshiKayo** [comment]
@HikariKnight Does RSU use the actually Linux client that Jagex provides or is this downloading the generic java file?

**Comment by ivanpu** [comment]
This is a launcher to the Java client, the one that is called now "Legacy" in the downloads page.
This is not the NXT, if that's what you meant.

**Comment by RyoshiKayo** [comment]
I've been back and forth with three different JMods and they have all said that they cannot support this issue. 

@HikariKnight Might just want to mark this ticket as wontfix

**Comment by HikariKnight** [comment]
@RyoshiKayo done, sorry i couldnt really be of help.
