### ISSUE TITLE
Resizable mode not working in funorb games

### ISSUE THREAD

**Issue by spellwork** [HikariKnight/rsu-client#134]
@HikariKnight Using linux mint, I have tried using resizable in both AoG and Arcanists, and in neither it worked. While it would grey out resizable as if I had chosen it, the screen would remain fixed. I have previously been able to use resizable on windows using the .prm files with the osrs client. If theres anything that could be done on your end or if you have a soloution I could implement I would appreciate it, thanks.

**Comment by HikariKnight** [comment]
not as far as i know. as the prm file is literally a text file containing java parameters.
and once the appletviewer has launched i have no control over what happens as all my client does is feed it the proper information to launch and make sure that java is configured properly (in terms of opengl support)

**Comment by spellwork** [comment]
its a bit bizzare, i didn't think there would be much you could do but decided i'd mention it. thanks for your response, i've got the games to work fine in the browser so i'll be doing that instead.
