### ISSUE TITLE
Uncomplete theme

### ISSUE THREAD

**Issue by ivanpu** [HikariKnight/rsu-client#19]
The theme still looks uncomplete also on Linux:
![rs-theme](https://f.cloud.github.com/assets/2607888/1351435/525c57c2-3725-11e3-82a5-5352d9553668.png)
I can understand the title bar, but is it possible to color everything else, without changing OS theme?
Also note the button hover effect.

**Comment by HikariKnight** [comment]
decided i wont be able to fix this as it would require a "special" gtk theme for the launcher itself where we have to make sure it works with the common gtk engines that are in use. However after this issue came up, i changed the theme so it does not affect the tabs but only objects inside them.
