### ISSUE TITLE
libcairo patch not available in the repository

### ISSUE THREAD

**Issue by Smarre** [HikariKnight/rsu-client#32]
Hi @HikariKnight,

By looking the repository, I can’t find any information about what you’ve done to the libcairo2.so in order to get it to work. In general I think it’d be good to insert some transparency to random blobs of binary in the repository, but the main problem is that it’s compiled against libpng12.so, which is not anymore present in modern distros (well, atleast in mine).

I don’t know if that fix is related to the crash I’m getting to ( http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=1486 ), but that’s about only idea I have left in order to debug this further.

**Comment by HikariKnight** [comment]
when/if i get some freetime (longer than 3 hours) i will look into making a ppa package for this and maybe have optional precompiled versions in the client.

**Comment by ivanpu** [comment]
> when/if i get some freetime (longer than 3 hours) i will look into making a ppa package for this and maybe have optional precompiled versions in the client.
This workaround no longer needed for ArchLinux with current cairo package.
IDK about other distros...

**Comment by HikariKnight** [comment]
@ivanpu
Will monitor this

**Comment by HikariKnight** [comment]
should not be needed anymore, patch to disable the built in libcairo-nogl will come in the future
