### ISSUE TITLE
Resizeable graphics option doesn't adjust to window size

### ISSUE THREAD

**Issue by Mishio595** [HikariKnight/rsu-client#43]
@HikariKnight 

When selecting the resizeable option for in-game graphics, the game doesn't expand to the max window size. I'm using an EWMH compliant tiling wm. The fullscreen option functions normally.

**Comment by HikariKnight** [comment]
might be because the game (or java?) expects an actual window container with a titlebar and frames, just a theory.

**Comment by Mishio595** [comment]
@bayanr Yes, that is exactly the problem.

@HikariKnight It is an actual window container. Tiling window managers have no reason for titlebars so they're omitted (although awesome has a way to enable them). It seems to me that the game doesn't recognize the forced size change of the window, but floating the window and manually resizing doesn't seem to work either. And as I've never had problems with java, I believe the game itself is the cause.

**Comment by bayanr** [comment]
Just going to add that this problem is nonexistent on awesome(default installation from Arch repos). I'm going to try to look into why this is the case.

**Comment by HikariKnight** [comment]
@bayanr tell us if you find out something. i will keep the issue open for now (few months) to wait for the results

**Comment by Mishio595** [comment]
Verified that Awesome does not have this issue. I wonder if it has to do with how awesome handles window sizing. Awesome's config is entirely in lua, so I think the window size that awesome passes to X also is lua readable, which might also be recognizable by the Java game client. Just a guess as BSPWM is controlled via shell commands to bspc (I assume the window information is passed directly to X).

**Comment by lerp** [comment]
It's to do with the way Java recognizes window managers. It has a hard-coded list of known non-reparenting window managers. A solution is to use `wmname` (http://tools.suckless.org/wmname) to tell Java you are using a non-reparenting window manager. Using `wmname LG3D` and then launching the program fixes the problem for me.

**Comment by Mishio595** [comment]
Just tested wmname. Works perfectly! Thanks so much
