### ISSUE TITLE
Multiple instances of RSU?

### ISSUE THREAD

**Issue by cwexperts** [HikariKnight/rsu-client#45]
In my experience with Windows client, starting multiple clients would create separate caches for each one and that allowed me to store separate names on login + separate graphical settings for my secondary account. But on Linux, when I load a secondary client, it just loads the original cache again while on windows I had jagexcache, jagexcache1, 2, etc. from all the isntances by the client + browser.

Any idea on how to achieve this on Linux?

**Comment by HikariKnight** [comment]
over 1 month with no reply, closing issue
