### ISSUE TITLE
-Dhttps.protocols=SSLv3

### ISSUE THREAD

**Issue by grawity** [HikariKnight/rsu-client#46]
Commit a1f7afdee6d55a12911cfe195c2e20125c5a3213 added the `-Dhttps.protocols=SSLv3` option. It doesn't explain however why it is needed &ndash; did it default to the ancient SSLv2, or did it have compatibility issues with the newer TLSv1.x?

Either way, though, with many sites (including likely Jagex) rushing to drop SSLv3 support, this will need to be adjusted to use some version of TLS.

**Comment by HikariKnight** [comment]
this was added in order to make prm files work over https with some help from jagex

**Comment by grawity** [comment]
That was a year ago; I am not sure it is any longer necessary.

In fact, testing it on Arch, `com.jagex.config=https://` does not work at all if SSLv3 is forced – it shows an error message without even attempting to connect. (The error dialog is unfortunately black-on-black.) I tried Oracle jre8, jre7, openjdk8, openjdk7, none of them work with SSLv3.

They all, however, automatically use TLS if I remove the forced `https.protocols` setting.

**Comment by HikariKnight** [comment]
ok will take a poke at it today when i get home hopefully

**Comment by HikariKnight** [comment]
i will have to email philip about this


anyway the reason for the line was to enable the use of prm files over https, it was not something that was needed but there was a few players that were on networks that only accepted https traffic, philip then put up a https link for the prms for those affected.

in short, no the default prm is not available through https
however it can be reached through https
https://www.runescape.com/k=3/l=$(Language:0)/jav_config.ws

**Comment by HikariKnight** [comment]
@grawity after some poking around on my own it seems like that some ciphers are used that are unsupported.
might be my test environment though

Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256


you get this if you apply
-Djavax.net.debug=all

**Comment by HikariKnight** [comment]
@grawity after some more testing (and me being stupid changing my test source and then run the installed client instead of the local test client) i got https working again and futureproofing it, should jagex change to TLS1.x

change the 
-Dhttps.protocols=SSLv3

to
-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

i will push out a fix for this as soon as i can
