### ISSUE TITLE
Portage package (for Gentoo)

### ISSUE THREAD

**Issue by JohnPeel** [HikariKnight/rsu-client#47]
I've created a portage package for rsu in my overlay at https://github.com/JohnPeel/dgby-overlay/blob/master/games-rpg/unix-runescape-client/unix-runescape-client-4.2.9-r1.ebuild

I've got it setup to automaticly update the config to use the system-java as well as update some settings depending on use flags.

I also noticed a problem with the config (the example). You give section names in the example config but when loading the config your client uses the "_" section.

It seems to work fine without a section...

Otherwise I think the package is fine.

**Comment by HikariKnight** [comment]
_ is a default section, it works the same way as no section (undefined secion) as the original conf files had no sections

**Comment by JohnPeel** [comment]
@HikariKnight I know, what I was saying was that there is an inconsistency between the example config and the default.

The example uses "Settings" and "Fixes" for section names, where the default uses "_". (rsu-client seems to only support the default section "_")

**Comment by HikariKnight** [comment]
@JohnPeel oh whops, i will take care of that when i get home today, my bad!

**Comment by HikariKnight** [comment]
@JohnPeel i am not familiar with portage, just curious if you made an installer for the client for gentoo

**Comment by JohnPeel** [comment]
I did, it's in my layman overlay. If people want to install it they either have to add my overlay to their layman or just download the ebuild to their local overlay. If you'd like I can create a small wiki page on it.

**Comment by JohnPeel** [comment]
This package pretty much does the same thing as the arch package, I just make a modification or two to the configs. A default config doesn't work on Gentoo because our java is a shell script. I just set the default java path to our system-wide java install location.

You can see the modifications here -> https://github.com/JohnPeel/dgby-overlay/blob/master/games-rpg/unix-runescape-client/unix-runescape-client-4.2.9-r1.ebuild#L45

**Comment by HikariKnight** [comment]
would be nice if you did then i will link the page in the Readme.md

**Comment by JohnPeel** [comment]
I would suspect anyone using Gentoo already knows how to do this, but here is a simple page with links for more information.

https://github.com/JohnPeel/dgby-overlay/wiki/Installing-rsu-client-on-Gentoo

**Comment by HikariKnight** [comment]
added to readme.md
