### ISSUE TITLE
minimap messed up.

### ISSUE THREAD

**Issue by NFAUG** [HikariKnight/rsu-client#49]
@HikariKnight     ive noticed that rezising dosent work as intended, and one of the problems is i have to quickly make it fullscreen before it loads otherwise FS dosent work, but when i get into game theres always this spot on the map thats messed up, its long rectangler. i took a screenshot and here it is.

https://www.dropbox.com/s/zco87dsj369x4s5/2015-02-20-121817_1600x900_scrot.png?dl=0

edit 1 : forgot this might be relevant, as the AUR install is broken i had to install via the 64bit installer.

edit 2 : after some further testing it appears to fix itself over time.

**Comment by HikariKnight** [comment]
hi @NFAUG your picture link is broken

also i will see if i can contact @ivanpu about the aur build

**Comment by ivanpu** [comment]
@HikariKnight 
Picture link worked for me few days ago, it looked like when you have "empty" chunks in Minecraft...

AUR build: I see there was version bump... I wonder how I missed the "outdated package" mail...

**Comment by NFAUG** [comment]
so sorry, i cleaned out my dropbox and thats not the only image i accidentally deleted. ill see if i can get it back up, i might have a copy.  or ill just take a new one since its still present if you guys still need it.

**Comment by ivanpu** [comment]
You can post images here... by just dragging them into text box ;)

**Comment by NFAUG** [comment]
it dosent seem to be happening anymore, and the game did do an update once i begin playing it. so maybe w/e they did on their end fixed it?

**Comment by ivanpu** [comment]
Might be, or might be corrupted cache that was reset by update.
I guess this issue can be closed now?

**Comment by NFAUG** [comment]
its back, 
![2015-02-23-180755_1600x900_scrot](https://cloud.githubusercontent.com/assets/11094033/6339774/04c4d4ac-bb87-11e4-99f1-4f2210caffad.png)

**Comment by kr0g3r** [comment]
I get the same thing using the official client.

**Comment by NFAUG** [comment]
oh, maybe its a bug on their end than, i was thinking it was the rsu-unix client.
