### ISSUE TITLE
How do I launch the client without the perl-wx dependency?

### ISSUE THREAD

**Issue by MushyBean** [HikariKnight/rsu-client#51]
I'm trying to see if I can get Old School Runescape to run on a Raspberry Pi using this client.
It probably won't run very well but it's worth a try.

I'm running the ARM version of ArchLinux and installed this client from the AUR repository which also installed most of the dependencies for me except for a few which couldn't be found.
I managed to manually install the remaining dependencies except for perl-wx which failed to build.

I tried to launch the client anyway since I'd read that perl-wx / Wx / WxPerl was only required for certain interfaces and is not needed for the actual client itself.
This was the result:

    WARNING: Running in fallback mode!
    rsu-queries will use the system perl so some API calls
    may not work until you install certain modules
    WARNING: Wx module not found, API calls using WxWidgets will not work

    WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work

    WARNING: LWP::Simple module not found, API calls using LWP::Simple will either use alternative methods

    Use of uninitialized value $apicall in substitution (s///) at /opt/runescape/rsu/apiquery.pm line 43.
    Use of uninitialized value $apicall in concatenation (.) or string at /opt/runescape/rsu/apiquery.pm line 46.
    syntax error at (eval 26) line 1, at EOF
            ...caught at /opt/runescape/rsu/apiquery.pm line 46.

Is there a special way to run the client without the need for perl-wx or is this error unrelated?
Thanks.

**Edit:** I've just thought, even if I could get the client to run, I'm guessing the only way to switch to Old School RS is via one of the interfaces that requires Wx?

**Comment by hostonnet** [comment]
Try downloading the Jar

```
wget runescape.com/downloads/jagexappletviewer.jar
```
Running it with

```
java -cp jagexappletviewer.jar -Dcom.jagex.config=http://YOURWORLDHERE.runescape.com/jav_config.ws -Xms256m -Xmx256m jagexappletviewer .
```
YOURWORLDHERE  should be changed with the world you need to use. somthing like oldschool76 etc.. i am not very sure as i don't play oldschool.

**Comment by MushyBean** [comment]
I ran:

    java -cp jagexappletviewer.jar -Dcom.jagex.config=http://oldschool33.runescape.com/jav_config.ws -Xms256m -Xmx256m jagexappletviewer .

and received:

    Exception in thread "main" java.lang.UnsatisfiedLinkError:
    /usr/lib/jvm/java-7-openjdk/jre/lib/arm/xawt/libmawt.so: libXtst.so.6: cannot open shared object
    file: No such file or directory
            at java.lang.ClassLoader$NativeLibrary.load(Native Method)
            at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
            at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
            at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
            at java.lang.Runtime.load0(Runtime.java:795)
            at java.lang.System.load(System.java:1062)
            at java.lang.ClassLoader$NativeLibrary.load(Native Method)
            at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
            at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
            at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1872)
            at java.lang.Runtime.loadLibrary0(Runtime.java:849)
            at java.lang.System.loadLibrary(System.java:1088)
            at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
            at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.awt.Toolkit.loadLibraries(Toolkit.java:1653)
            at java.awt.Toolkit.<clinit>(Toolkit.java:1682)
            at java.awt.Component.<clinit>(Component.java:595)
            at app.appletviewer.b(appletviewer.java:983)
            at jagexappletviewer.main(jagexappletviewer.java:7)

I'm wondering if `java.lang.UnsatisfiedLinkError` means it didn't like the oldschool33 URL.
I tried changing the world number but it didn't make a difference.

**Comment by hostonnet** [comment]
Look like something wrong with libXtst.so

I checked url with

```
curl http://oldschool33.runescape.com/jav_config.ws
```

That shows something, looks good.

Maybe try oracle java and see if it works.

**Comment by ivanpu** [comment]
> libXtst.so.6: cannot open shared object
> file: No such file or directory

You need to install package `libxtst`. It is an optional dependency for `jre7-openjdk`, and hence most likely was not installed yet.

**Comment by MushyBean** [comment]
> You need to install package `libxtst`.

That was it!
Thanks for the help guys, OSRS is now running on the Pi.
At the moment there's no audio and obviously it would be nice to try the RSU-Client in the future, but for now this is fine.

**Comment by ivanpu** [comment]
Glad to help.
I think I'll add this to the AUR package.

**Comment by ivanpu** [comment]
@HikariKnight may shed more light on the original error.

**Comment by HikariKnight** [comment]
@MushyBean @ivanpu @hostonnet 

<pre>runescape client.launch.runescape --prmfile=oldschool.prm</pre>

should let you launch directly

<pre>runescape help</pre> if you want list all commands that can be passed to rsu-query
<pre>runescape [command] help</pre> if you want more info about a command (without brackets)

**Comment by MushyBean** [comment]
>     runescape client.launch.runescape --prmfile=oldschool.prm
> 
> should let you launch directly, and i belive when you launch it like this it will not use Wx if its not available :)

Many thanks, that worked.
It does still warn me about Wx but the client launches without problem.

**Comment by HikariKnight** [comment]
@MushyBean ye its just generic warnings i made for missing modules to make it easier to see "what am i missing" instead of "why doesnt this work" :P
