### ISSUE TITLE
Remove dependency on external file sharing sites

### ISSUE THREAD

**Issue by ivanpu** [HikariKnight/rsu-client#52]
We now have installers provided using external file sharing site. There was already one problem with previous site, that blocked access due to high traffic. But why use external site at all, when GitHub provides the needed feature?

## [GitHub Releases](https://github.com/blog/1547-release-your-software)
They are extending the existing tags: you can add (markdown formatted) description to it, and attach binary files for download. They are even already [exist](https://github.com/HikariKnight/rsu-client/releases) by default for each tag, and contain permalinks to source code for that tag. All is left to do, is click the relevant "Edit tag" button, and add the binaries.

What do you think, @HikariKnight ?

**Comment by ivanpu** [comment]
[Known limitations](https://help.github.com/articles/about-releases/#limitations-on-binary-files):
> At this time, we do not place any limits on the size of binary uploads nor the bandwidth used to deliver them.

**Comment by HikariKnight** [comment]
@ivanpu i will look into it next week when i have some more time as alot of stuff is happening for me lately, but i do like the idea and it will make giving out the installers easier for us

**Comment by HikariKnight** [comment]
finally got around to do this, adjusted readme.md to reflect this change and removed copy.com links from the frontpage.

closed
