### ISSUE TITLE
Something is wrong with the PPA

### ISSUE THREAD

**Issue by Mikaela** [HikariKnight/rsu-client#53]
@HikariKnight on Ubuntu 14.10 upgrading the client fails and same with `dpkg --configure -a`.

```apt
Setting up runescape (201503311854~git-master~ubuntu14.10.1) ...
syntax error at /var/lib/dpkg/info/runescape.postinst line 19, near "system"
Execution of /var/lib/dpkg/info/runescape.postinst aborted due to compilation errors.
dpkg: error processing package runescape (--configure):
 subprocess installed post-installation script returned error exit status 255
Errors were encountered while processing:
 runescape
```

**Comment by HikariKnight** [comment]
i am aware of it  and it will be fixed later today(as in a few hours when i am allowed to request builds again).
i already went out and notified people on the forums and on [twitter](https://twitter.com/rsHikariKnight/status/582990670484262912) when the issue occured

for the time being you can run
sudo rm /var/lib/dpkg/info/runescape.*

then install this deb package until the PPAis fixed (should be up and running again tomorrow as an universal ETA)
https://copy.com/QifWAZEsFJs3M6uo/RSU/runescape_4.3.2_all.deb?download=1

**Comment by HikariKnight** [comment]
PPA package fixed, should get published within the next hour
