### ISSUE TITLE
Packaging file to /usr/local/

### ISSUE THREAD

**Issue by ivanpu** [HikariKnight/rsu-client#55]
The directory `/usr/local/` is reserved for the computer user/owner management, and packages should not modify it's content.

In this case, the single script it contains should go under some subdirectory of the client (`/opt/runescape/...`).

**Comment by Mikaela** [comment]
I would use just `/usr`, but `/opt` might be better for projects like this as Steam and Google Chrome are putting them there I think.

**Comment by ivanpu** [comment]
@Mikaela, it is already packaged (usually) to `/opt`.
This issue is about one specifc file: [xdg-open](https://github.com/HikariKnight/rsu-client/blob/master/runescape/templates/packaging/usr/local/bin/xdg-open)

**Comment by HikariKnight** [comment]
I guess the only way for you then would be to notify the user that they should copy the file there if they are on Xfce to make the jagex-jav protocol work.
I was able to avoid this by using the postinst script in the debian package/PPA unless AUR has something similar that works that way.

**Comment by ivanpu** [comment]
Yes, there are postinstall scripts, but your sed script modifies nothing in the current version of `xdg-open` (1.1.0) in ArchLinux.

**Comment by HikariKnight** [comment]
@ivanpu 
as long as the xdg-open in /usr/bin contains the line
<pre>elif xprop -root 2> /dev/null | grep -i '^xfce_desktop_window' >/dev/null 2>&1; then DE=xfce;</pre>

it will be ok to not include the xdg-open script from the client as your xdg-open will be of the newer versions that have the xfce4 issue fixed :)

**Comment by ivanpu** [comment]
Ok, then this is not needed at Arch :)

P.S.
Don't forget issue #54.
