### ISSUE TITLE
"Play now" nothing happens, how to debug?

### ISSUE THREAD

**Issue by ktmn** [HikariKnight/rsu-client#56]
I'm on Windows 8.1, downloaded the installer, hit Play now and nothing happens. How do I find out what's the problem?

**Comment by ivanpu** [comment]
Did you run the updater? It's the next button.

**Comment by ktmn** [comment]
Updated jagexappletviewer.jar and rsu-api, no change unfortunately.

**Comment by ivanpu** [comment]
Just tested on Window 7 laptop... yeah, launching from command line gives no output :disappointed:

Ok, next thing to check: do you have java installed?

**Comment by ivanpu** [comment]
@HikariKnight
I'll add "me too" for this issue - I have no idea why it's not working at Windows 7.

**Comment by ktmn** [comment]
I got Java 8 U 31. No output from command line either. It just starts the client and returns.

**Comment by ivanpu** [comment]
Got it working (_using Java 8u40_): Goto settings, in `preferred java` select `custom-java` and then `browse` for the binary.

**Comment by ktmn** [comment]
Yep that did it, thanks.
