### ISSUE TITLE
Black bars

### ISSUE THREAD

**Issue by ktmn** [HikariKnight/rsu-client#57]
How come the client has black bars on top and bottom? 

Official client doesn't have these bars, I though this one was based on it, so how could they appear?

http://i.imgur.com/9RZWwxh.png

I feel like there's a performance improvement to my chunk loading times with this client and would like to use it, but not with the black bars.

Any way to remove them?

Thanks.

**Comment by HikariKnight** [comment]
@ktmn
The black bars removal code that mod Philip wrote, does not work in java8. Try tell the client to use java7 or java6 instead and have your system keep using java8


Also about the chunk loading is improved by letting java use multiple processor cores for loading new chunks, i will link you the prm lines that are applied with the java optimization option enabled in the Linux client

**Comment by ktmn** [comment]
Installed Java 7u80 and set the client to use it, black bars are gone, thanks.

**Comment by HikariKnight** [comment]
Whoops i forgot to link you the parameters

- XX:+AggressiveOpts
-XX:+UnlockExperimentalVMOptions 
-XX:+DisableExplicitGC
-XX:+TieredCompilation
-XX:ReservedCodeCacheSize=256m
-XX:+UseAdaptiveGCBoundary
-XX:SurvivorRatio=16
-XX:+UseParallelGC
-XX:+UseParallelOldGC
-XX:+AggressiveOpts


It's the ones mentioning parallel
However the others help performance and are used with it too.

For 32bit java you also need the -client
Parameter and for java 64 bit you need the CompressedOOPs parameter (can't remember exact name on top of my head, will check after I have posted this reply)

**Comment by HikariKnight** [comment]
The dot is meant to be a dash -

For Java 64 bit the equivalent of the -client parameter is -XX:+UseCompressedOops

It fixes several stuttering issues related to textures
