### ISSUE TITLE
rsu client works and then after a computer restart I can't open it anymore...

### ISSUE THREAD

**Issue by SourSkittles** [HikariKnight/rsu-client#60]
okay so idk what just happened but I installed this client and after a bit of fidling with the settings I got it to finally start up the runescape client like it should, well I ended up restarting my computer shortly after and well now I can't get the rsu client to load up at all every time I start it up it seems to go and just terminate itself without any sorta error or anything.

I've tried to reinstall the rsu client, I've tried the portable version, I've tried restarting my computer again just encase it decided to work again after a restart and well I get nothing but it terminating before anything even pops up..

Anyways I'm running windows 8.1, I don't have any antivirus software so that wouldn't be the issue there and it was working just fine before I did a restart :/ so hopefully you can help me figure this issue out @HikariKnight

**Comment by SourSkittles** [comment]
Well I figured out what the error is that's happening by just loading up the rsu-query.exe (which is where it's crashing at to begin with)

this is the error that pops up for a split second and then closes itself.
" LWP: :Simple module not found, API calls using LWP: :Simple will either use alternative methods
Reading value from "newschannel"
Setting script data newschannel to runescape
Fetching the current playercount.
Can't locate object method "new" via package "LWP: :UserAgent" at D:/Games/Runescape/rsu/framework/modules/updater/download/sysdload.pm line 45.
Compilation failed in require at (eval 58) line 2.
Begin failed--compilation aborted at (eval 58) line 2.
 ...caught at D:/Games/Runescape/rsu/apiquery.pm line 46."

That is all of the error and it closes a split second after it spits out all that information but hopefully this can help you figure out what is happening a little easier :s

**Comment by HikariKnight** [comment]
it is an odd issue that can happen on windows sometimes

go into the directory "%TEMP%" and delete the folder that starts with the name 

par-

followed by some random numbers
that directory is used to store the perl runtime on windows.

then relaunch the client (will take longer as it will recreate the directory from scratch as if it is running for the first time)
if that doesnt work then delete the par- folder again and reinstall the client.

**Comment by SourSkittles** [comment]
Yea I literally just thought of that as I was looking through my process lasso log and noticed the temp folder, was just about to come back and say I finally got it working lmfao >..< thanks though haha I'll at least remember this next time I have this issue.

**Comment by HikariKnight** [comment]
i will close this then :)

**Comment by SourSkittles** [comment]
Okay this is getting very annoying, idk what to do really other than go back to using the actual rs client but I don't want to because of the options that your client lets me do.. When ever I close your client for whatever reason I can't even re-open it again later unless I go in to the temp folder and delete the folder that your client makes :/

**Comment by HikariKnight** [comment]
Could be an issue on windows 8? Idk

If you want I can give you all the lines that you need in the official prm file to get the same performance in the official client.
Sadly you cannot move the cache in the official client without symlinks though

**Comment by SourSkittles** [comment]
who knows tbh, and nah it's fine (the official prm file would do the same thing anyways with the rsu client as I already tested it) I'm using the prm file that I found on you twitter page for "the high end computer" since my computer is more high end. 

Anyways I just automated the deletion of the folder (after a bit of fiddling around with bat files and other tools since it was getting annoying doing it manually all the time) that's created so it's not much of an issue now for now :x

**Comment by HikariKnight** [comment]
just as a heads up about that par- folder though
if i have to recompile the binary (rsu-query.exe) in the future it is not going to have a random set of numbers after it but it will be named par-rsu.
just so you are aware of it :)

it will be mentioned in the patch notes if it does happen but i highly doubt it as i havent had to recompile since version 1.5.x or something like that.

**Comment by SourSkittles** [comment]
okay haha not a big problem or anything as the way I have my stuff set up it just searches for the "par" part of the folder so no matter what happens as long as that first part doesn't change then I won't have to edit my files.
