### ISSUE TITLE
Unexpected behavior - doesn't open

### ISSUE THREAD

**Issue by madyoda** [HikariKnight/rsu-client#61]
```
tom@TomPC ~ # runescape 
07:13:17 PM: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
07:13:17 PM: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
tom@TomPC ~ # rsu-settings           
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
07:18:17 PM: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
tom@TomPC ~ # 
```

I get this message whenever I try to open rsu client. Any idea?

I'm running on Arch Linux, AwesomeWM DE. Same behavior on GNOME 3.16.

**Comment by ivanpu** [comment]
I'm getting the same output (and many more), but in my case everything works fine.
Although, I'm using perl-wx 0.9923-1, while AUR have 0.9927-3.

Is it new installation?
If not, good bet will be to rebuild all perl related packages that are installed from AUR.

**Comment by madyoda** [comment]
New installation. If I remember correctly I was getting a weird perl issue last time it tried to upgrade. I'll go try rebuild that now.

**Comment by madyoda** [comment]
Ah, yes. This error when trying to install perl-wx.
```
Test Summary Report
-------------------
t/01_load.t         (Wstat: 139 Tests: 1 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 6 tests but ran 1.
t/04_userdata.t     (Wstat: 0 Tests: 65 Failed: 0)
  TODO passed:   25, 49, 57
Files=23, Tests=784,  9 wallclock secs ( 0.11 usr  0.02 sys +  2.81 cusr  0.43 csys =  3.37 CPU)
Result: FAIL
Failed 1/23 test programs. 0/784 subtests failed.
Makefile:1278: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
==> ERROR: A failure occurred in check().
    Aborting...
==> ERROR: Makepkg was unable to build perl-wx.
```

Googling doesn't seem to return anything. Nor does downloading the tarball & makepkg'ing it.

**Comment by ivanpu** [comment]
From comments in perl-wx package it looks like the problems with it were resolved...
@madyoda , do yous still have the problem, or can this issue be closed?

**Comment by TheWiseNoob** [comment]
I'm having this same problem. I couldn't get the latest perl-wx to build because of this.

**Comment by ivanpu** [comment]
@TheWiseNoob 
Did you try to build 'perl-alien-wxwidgets' with the wxgtk2.8 hack?
It is there for the cases when it can't be build with wxgtk3.

Although in my case all works well with wxgtk3...

**Comment by HikariKnight** [comment]
Closed as there have been no response in a month.
Assuming issue Is resolved.
