### ISSUE TITLE
"sh: 1: aoss: not found" when selecting alsa as audio driver

### ISSUE THREAD

**Issue by ScoreUnder** [HikariKnight/rsu-client#62]
I use alsa so I thought it would be beneficial to set that in the options. This happened:

```
sh: 1: aoss: not found
```

The client would not start up until I switched to the default.
I don't use OSS.

**Comment by HikariKnight** [comment]
you still need the program "aoss" to force oracle java to use alsa sadly as the openjdk method does not work on it(hence aoss as a dependency in packages), openjdk uses a different method to get alsa working since aoss does not work with it.

**Comment by HikariKnight** [comment]
Over 1 month without reply, auto closed
