### ISSUE TITLE
Opening program doesn't seem to do anything!

### ISSUE THREAD

**Issue by IceQubed** [HikariKnight/rsu-client#65]
Hi @HikariKnight - on my chromebook (running ubuntu trusty with xfce4) I've attempted to use both the installer and the console apt-get command method to install this program.

The icon/shortcut is in my launcher menu, however when I click it nothing happens.

When I try to run the command "runescape" in terminal, I get this: http://pastebin.com/9MtGKuLT

Have I done something stupid? Any idea why it's not running? Thanks.

**Comment by HikariKnight** [comment]
<pre>Response from RSSFEED: Timed out while waiting for socket to become ready for reading
 
 
This is the RSS contents we found:
Timed out while waiting for socket to become ready for reading
 
 
Content must be RSS|RDF|ScriptingNews|Weblog|reasonably close at /opt/runescape/rsu/framework/Perl5lib/XML/RSSLite.pm line 32.</pre>

seems like it failed to fetch the newsfeed and crashed, thought i fixed this crash months ago :o

you should be able to get ingame by simply

<pre>runescape client.launch.runescape</pre>

if you want to use a spesific prm file then (oldschool as example)
<pre>runescape client.launch.runescape --prmfile=oldschool.prm</pre>

if you want to access the updater then
<pre>runescape client.launch.updater</pre>

i will have a closer look at your pastebin output for more info. but if it is purely a timeout issue there is not much i can do but to add another condition for it to skip it and hope it works.

**Comment by HikariKnight** [comment]
is this still a problem @IceQubed ?

**Comment by HikariKnight** [comment]
closed due to inactivity and no response
