### ISSUE TITLE
Add prm for Darkscape (pasted in here)

### ISSUE THREAD

**Issue by doorknob60** [HikariKnight/rsu-client#67]
I don't have time to figure out how to fork and submit a pull request, but I have a working darkscape.prm file for the recently released Darkscape https://darkscape.runescape.com/. Here it is:

-Djava.class.path=jagexappletviewer.jar
-Dcom.jagex.config=http://www.runescape.com/jav_config_beta.ws
-Xmx512m
-Xss2m
-Dsun.java2d.noddraw=true
jagexappletviewer

**Comment by ivanpu** [comment]
Here is a *very* simple method to create a working prm:
`cp  runescape-beta.prm darkscape.prm`
:wink:

**Comment by Emp-M** [comment]
Hikari has already created a prm file for darkscape, [found here](https://www.copy.com/s/t%3AqrRtTZWItMHrc6L0%3Bp%3A%252Fprms/darkscape/rsu/runescape_darkscape.prm%3Boid%3A1164), and placed in:
    ~/.config/runescape/share/prms/

The other alternative is to open the launcher, click settings, and where it says Paramater File: rename it to "runescape-darkscape.prm" without quotes. Then you change to the Client Settings tab, and change the Config URL to http://www.runescape.com/jav_config_beta.ws and save. You now have a new prm to load that will be between runescape.prm, and runescape-beta.prm.

**Comment by ivanpu** [comment]
> Hikari has already created a prm file for darkscape, [found here](https://www.copy.com/s/t%3AqrRtTZWItMHrc6L0%3Bp%3A%252Fprms/darkscape/rsu/runescape_darkscape.prm%3Boid%3A1164), and placed in: ~/.config/runescape/share/prms/

Oh, sorry, he (@HikariKnight)  should have placed them here:
https://github.com/HikariKnight/rsu-client/tree/development/runescape/share/prms
That's where I was checking...

**Comment by HikariKnight** [comment]
Reason i didn't place it there was because I didn't have time and was on a system without git or the ssh keys needed to sign into github, it will most likely be sorted out today

**Comment by HikariKnight** [comment]
done
https://github.com/HikariKnight/rsu-client/releases/tag/v4.3.4
