### ISSUE TITLE
Weird graphical problem

### ISSUE THREAD

**Issue by LevyWilson** [HikariKnight/rsu-client#69]
I'm getting a weird graphical problem when I load the client. I'll let the screenshot speak for itself.

Running Lubuntu 14.4

@HikariKnight

![2015-09-18-175659_1280x720_scrot](https://cloud.githubusercontent.com/assets/10651328/9972227/73481bf4-5e30-11e5-8274-8ade1aa00e40.png)

**Comment by HikariKnight** [comment]
ehh i have no idea what is happening here.
either a driver issue or a cache issue is my best guess sadly

**Comment by HikariKnight** [comment]
no word back, over 1 month passed so closing this.
if issue resurfaces the please re-open the issue or make a new issue
