### ISSUE TITLE
OSRS stops at "Loaded update list"

### ISSUE THREAD

**Issue by clotifoth** [HikariKnight/rsu-client#70]
@HikariKnight 

Running Trusty Ubuntu on an Acer c720 using Crouton. I have gotten the client to work prior to today.

I have tried clearing the cache, reinstalling rsu-client, allocating more memory, different versions of Java (tbh a given jre shouldn't be a dependency here, or at least not the ancient openjdk-6 but that's a different issue) restarting, and running as administrator. University does not block the network in any way that would prohibit this from working- works fine on my Windows 8 laptop.

This issue also occurs with any other .prm I select, in varying forms- runescape.prm stops at Checking for updates (98%)

Please help! :)

**Comment by clotifoth** [comment]
If I run the client as root, it loads fine. This is still bad behavior and it shouldn't be necessary to run rsu-client.

**Comment by HikariKnight** [comment]
Running as root should not be necessary. Only thing I can ask you to try is to assign a different directory to be used as the jagexcache or try loading the config through https (change the config url in settings) since once the client loads, my scripts don't do anything else.

**Comment by HikariKnight** [comment]
no reply for 1 month, auto closed

**Comment by SullyJHF** [comment]
Hey HikariKnight, this same thing happens to me on an ASUS C300 chromebook, running as root doesn't fix it, changing the config to https shows an error message and then doesn't open. I don't know how to change the jagexcache directory so if you could point me in the direction to do that that would be great.
Here is an error message that showed when trying to use runescape.prm:
```
Error: client.init:1240 sun.reflect.NativeMethodAccessorImpl.invoke0 sun.reflect.NativeMethodAccessorImpl.invoke:62 sun.reflect.DelegatingMethodAccessorImpl.invoke:43 java.lang.reflect.Method.invoke:498 Rs2Applet.a:29 Rs2Applet.init:503 app.appletviewer.a:846 jagexappletviewer.main:34 | java.lang.RuntimeException | 
```
This doesn't show when I try oldschool.prm (which is what I want), although when I try to run oldschool as root it says:
```
Home directory not accessible: Permission denied
```

**Comment by HikariKnight** [comment]
OK from the clients directory

share/configs/settings.conf

There should be a line about cache directory

**Comment by HikariKnight** [comment]
PS: change default into the location you want the cache (make sure the folder exists! And I would recommend it to be an empty folder)

**Comment by SullyJHF** [comment]
it now says
```
sh: 1: aoss: not found
```
When I change it to either portable, or something else e.g. $HOME/runescape/

**Comment by SullyJHF** [comment]
Neither of these things worked, I tried a folder in /usr/share and running as sudo, it still got stuck at loaded update list, changing it to portable still didn't work, and it still says `Home directory not accessible: Permission denied` as soon as the "Loaded update list" bit shows on the loading bar, which gets me thinking that it's trying to access something after loading the update list, but can't, even when running in sudo.

**Comment by SullyJHF** [comment]
Ok don't worry about this I've got it working fully now, even without sudo, the `CRAS add failed` was the clue. It was because there was a version mismatch of some sound driver in my chroot, meaning sound didn't work at all, causing runescape to hang for some reason on startup, when it tried to play the intro sound I guess.

Well, glad this is fixed now, I can finally play runescape on my chromebook :+1:
