### ISSUE TITLE
debian install

### ISSUE THREAD

**Issue by subject546** [HikariKnight/rsu-client#72]
hi,

please change the title from "Installation on Debian" to "Installation on ubuntu based systems"
assing ppa's on a pure debian system could leave you with a broken system.. debian (or something that is close to it) users should just build from source.
https://wiki.debian.org/DontBreakDebian

subject546

**Comment by HikariKnight** [comment]
the ppa packages i provide are debian compatible as they do not rely on any other ppas, only base packages that are available in both ubuntu and debian.

the packages are the source as they are all scripts, there is nothing to build.

**Comment by subject546** [comment]
ah then it's fine.. i was alarmed to fast ;p

**Comment by HikariKnight** [comment]
Ye last thing i want to do is break someones system :)
