### ISSUE TITLE
RuneScape Facebook Integration

### ISSUE THREAD

**Issue by fusion809** [HikariKnight/rsu-client#74]
Hi,

I have installed RSU 4.3.4 via the .run installer (which I must say is great, whoever thought to create a .run installer deserves a good pat on the back) and while I know this may be on Jagex's turf not RSU's I was wondering why in some desktop environments (DEs) the Login with Facebook button doesn't work (that is, it does not open my web browser to log me in with Facebook) while in others it does and what might be done to get it to work in all DEs. I have set my default web browser with `xdg-mime` but this does not seem to have fixed this problem. 

Thanks for your time,
Brenton

@HikariKnight

**Comment by HikariKnight** [comment]
Its because of how jagex opens the browser through the applet. The api they use is not reliable on all desktop environments. Sadly I do but know how the api determines what desktop environment it is on and how it checks for browsers.

**Comment by ivanpu** [comment]
From my experience, it works on xfce and lxde, but not on cinnamon.
Can't remember about other DEs I've used.

**Comment by HikariKnight** [comment]
closed due to inactivity
