### ISSUE TITLE
Can't log in osrs

### ISSUE THREAD

**Issue by edwsqa** [HikariKnight/rsu-client#75]
@HikariKnight , after pressing "log in" button client crashes. Then terminal says this:

A fatal error has been detected by the Java Runtime Environment:

  Internal Error (os_linux_zero.cpp:285), pid=16907, tid=2096100464
 fatal error: caught unhandled signal 4

 JRE version: 6.0_36-b36
 Java VM: OpenJDK Zero VM (23.25-b01 mixed mode linux-arm )
 Derivative: IcedTea6 1.13.8
 Distribution: Ubuntu 12.04 LTS, package 6b36-1.13.8-0ubuntu1~12.04
 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /home/mazku/.config/runescape/bin/hs_err_pid16907.log

 If you would like to submit a bug report, please include
 instructions how to reproduce the bug and visit:
   https://bugs.launchpad.net/ubuntu/+source/openjdk-6/

Aborted (core dumped)

**Comment by edwsqa** [comment]
nvm i installed java 7 or something and it worked lol :P

**Comment by HikariKnight** [comment]
You were using a different JVM with openjdk6.
Rusescape supports only the default JVMs
