### ISSUE TITLE
Fedora instruction does not install all dependencies.

### ISSUE THREAD

**Issue by HeartyJ** [HikariKnight/rsu-client#76]
Hello! So, as the title says, running Fedora 22 it fails to install perl-Wx. Perl-Wx seems to be needed to display things. Further, I get an warning stating: "WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work". Haven't been able to find the dependency for this. Here's how I would fix it:  sudo dnf install perl "perl(List::MoreUtils)" "perl(Config::IniFiles)" "perl(Archive::Extract)" "perl-Wx". Let me know if I can be of further assistance.

**Comment by HikariKnight** [comment]
WxWebView is a newer library that is yet to make it to the main repos as its still too unstable. It's available in newer versions of wx-Perl. Depending on what comes first (newer wxPerl or nxt) I might make use of WxWebView for those that have it available. As of now it is just a debug warning for the possible future.
Also will update the readme to correct the capitalization

**Comment by HikariKnight** [comment]
done
