### ISSUE TITLE
hey, need some help :) @HikariKnight

### ISSUE THREAD

**Issue by jonnyjamm** [HikariKnight/rsu-client#77]
@HikariKnight  hey dude im trying to get you client, but im new to ubuntu ive done the things you said but one the first command it said "sudo apt-add-repository command not found" could you please help :)

**Comment by HostOnNet** [comment]
Run

```
sudo apt-get install software-properties-common python-software-properties
```

**Comment by HikariKnight** [comment]
What @hostonnet said

**Comment by HikariKnight** [comment]
closed as its been over a month since last reply

**Comment by jonnyjamm** [comment]
cheers mate :) you really help us out :)
