### ISSUE TITLE
License

### ISSUE THREAD

**Issue by quetea** [HikariKnight/rsu-client#80]
@HikariKnight whats the programs license? i cant see anything here regarding copyright

**Comment by ivanpu** [comment]
GPL2: [rsu-client/runescape/COPYING](https://github.com/HikariKnight/rsu-client/blob/master/runescape/COPYING)

**Comment by quetea** [comment]
should that not be in the root folder, or at least somewhere obvious?

**Comment by ivanpu** [comment]
Can't find where, but I remember that @HikariKnight said once that he can't move files now out of subdirectory due to some PPA restrictions.
He may be able to explain this better...

**Comment by quetea** [comment]
aah, still, a coyping link in the root directory would be a good way around that

**Comment by ivanpu** [comment]
> aah, still, a coyping link in the root directory would be a good way around that
I actually agree :+1:

**Comment by HikariKnight** [comment]
pulled
