### ISSUE TITLE
rsu-client-master/runescape/share/cache/jagexappletviewer.preferences (No such file or directory)

### ISSUE THREAD

**Issue by quetea** [HikariKnight/rsu-client#81]
java.io.FileNotFoundException: ~/bin/rsu-client-master/runescape/share/cache/jagexappletviewer.preferences (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at app.m.b(m.java:53)
        at app.appletviewer.a(appletviewer.java:501)
        at jagexappletviewer.main(jagexappletviewer.java:34)
Exception in thread "main" java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at app.appletviewer.a(appletviewer.java:507)
        at jagexappletviewer.main(jagexappletviewer.java:34)

wat

**Comment by ivanpu** [comment]
> wat

This looks like you installed/unpaked the client into `~/bin/rsu-client-master` and have forced the cache directory into `runescape/share/cache` subdirectory of it.
This exception comes from the Jagex code, that it can't find it's cache files...

Did you create this `~/bin/rsu-client-master/runescape/share/cache` directory?
And do you have write access to it?

By default your home directory is used, so Jagex's code might assume that this directory already exists and is writable...

**Comment by quetea** [comment]
i just unpacked the archive to ~/bin with ark, literally havent changed any of the default configuration

**Comment by ivanpu** [comment]
Then you shouldn't have the `cache` directory yet.
Go check, create it if needed, and try again.

**Comment by quetea** [comment]
why on earth doesnt it just come with one? oh well
now im getting this
Exception in thread "main" java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at app.appletviewer.a(appletviewer.java:507)
        at jagexappletviewer.main(jagexappletviewer.java:34)

has anyone else tested it on fedora 23 yet? because i dont have any idea why this doesnt work

**Comment by ivanpu** [comment]
[java.awt.HeadlessException](http://docs.oracle.com/javase/7/docs/api/java/awt/HeadlessException.html):
> ```java
public class HeadlessException
extends UnsupportedOperationException
```
Thrown when code that is dependent on a keyboard, display, or mouse is called in an environment that does not support a keyboard, display, or mouse.

Usually this means that you have installed only "headless" packages of Java, and not the whole JRE.

**Comment by HikariKnight** [comment]
> java.io.FileNotFoundException: ~/bin/rsu-client-master/runescape/share/cache/jagexappletviewer.preferences (No such file or directory)

the client should generate the folders and files itself, no idea why it wont do it here, might have to manually make the cache folder

**Comment by quetea** [comment]
i installed projectlibre earlier last night and it seems to have installed whatever was missing, fairly surprised to see that fedora is distributed without the full JRE

**Comment by ivanpu** [comment]
@quetea 
Initially installed packages depend on what the distribution manager deems needed.
For example ArchLinux comes with almost nothing (part of KISS principle) and Ubuntu comes with some bloat. After the initial setup is *up to the users* to install what they need.

Distributions like Mint that have Java-based software installed by default, do have some JRE (usually OpenJDK or Oracle) installed too. Sometimes Java is not needed for GUI, but just as platform for GUI-less program, and then headless packages are enough.

In Fedora case, the instructions are here: https://fedoraproject.org/wiki/Java

Anyways, if you just did fresh installation of Linux it's your duty to verify that you have all the software that you'll need. All unverified assumption are just that: assumptions.


Saying all that, I have never installed Fedora, and do not know what software it have installed by default.

**Comment by quetea** [comment]
if youre gonna install some of the JRE why not just go the whole hog? oh well

**Comment by HikariKnight** [comment]
If you run a server then you want the least overhead when running stuff, hence why packages get split up like that

**Comment by HikariKnight** [comment]
closed as there have not been any activity in over a month

**Comment by bpsizemore** [comment]
Had this same issue recently. Manually made the cache folder and then realized I hadn't installed Java yet (fresh install of Fedora). However, the installer has a script that says what dependencies are necessary to install. If I recall it did not require me to install java before the installation. I'll double check however.

**Comment by bpsizemore** [comment]
My mistake, I didn't read the top line that says "All of these require Java." Thanks for making this client!
