### ISSUE TITLE
RSU 4.3.5 is now in the Entropy repositories

### ISSUE THREAD

**Issue by fusion809** [HikariKnight/rsu-client#83]
Hi,

Yesterday the [RuneScape Unix Client 4.3.5](https://packages.sabayon.org/show/unix-runescape-client,161120,sabayonlinux.org,amd64,5,standard) was added to the Entropy repositories. Entropy is the package manager of Sabayon Linux (a Gentoo derivative). I thought this bit of news might be helpful for you (@HikariKnight) to add to this repo's README.

Thanks for your time,
Brenton

**Comment by HikariKnight** [comment]
Hey this is sweet, could you also give me the command if any to install it too?

**Comment by fusion809** [comment]
Sure `sudo equo i unix-runescape-client`.

**Comment by fusion809** [comment]
I just forked this project, if you would prefer I can add these additions myself, and then do a pull request.

**Comment by HikariKnight** [comment]
pulled and merged and sorted out
