### ISSUE TITLE
Troubles with installation 

### ISSUE THREAD

**Issue by ashdouglas95** [HikariKnight/rsu-client#87]
Installation on Debian

Open the Terminal program and type in the following commands:
```bash
echo "deb http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9BA73CFA
sudo apt-get update && sudo apt-get install unix-runescape-client
```
Everything worked until I got to Sudo apt-get install unix-runescape-client
 at that point it told me Unable to locate package unix-runescape-client

Am I doing something wrong/missing anything for proper download? Or is it simply not compatible

**Comment by ivanpu** [comment]
Did you had any error messages in the previous steps?
I do not use Debian, so can't tell anything about correctness of the commands, but they should work.

P.S.
I've edited the commands to be easier to read.

**Comment by ashdouglas95** [comment]
Well if you are 100% positive your way works. How do I go about completely restarting and retrying from step one using your method?

**Comment by HostOnNet** [comment]
Which version of debian you are using ? I read it is not recommended to use ppa in debian ?  I mostly use Ubuntu, had a installed a debian 8 yesterday for testing, if it is same version, i can try and see if it works.

**Comment by HikariKnight** [comment]
the
<pre>Unable to locate package unix-runescape-client</pre>

means that the
```bash
sudo apt-get update
```
must have failed

**Comment by HikariKnight** [comment]
closed due to inactivity
