### ISSUE TITLE
Keyboard Input

### ISSUE THREAD

**Issue by Devodorax** [HikariKnight/rsu-client#88]
@HikariKnight When playing the game, keyboard seems to send random input, most commonly resulting in the camera spinning in one direction, and only one specific character can be typed regardless of what key.

**Comment by ashdouglas95** [comment]
https://www.youtube.com/watch?v=3u_QolSJYoY
https://www.youtube.com/watch?v=HLdPepraVGA

I did everything through these video's.

**Comment by HikariKnight** [comment]
No idea what causes it but i believe it is related to a weird bug in the game client itself.
i remember having the issue on my minipc but not on any of my other computers so it might be cpu based too

**Comment by ivanpu** [comment]
Might be outdated libraries, or some java bug... what java do you use?
`$ java -version`
