### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by GamingFTW** [HikariKnight/rsu-client#90]
I've been trying to get runescape on Tumbleweed OpenSuse, but i've been having some trouble.
The first error I got was "permission denied." I have all the dependencies installed so I don't know that is going wrong.
The error I have now is a fatal error:
Fatal Error: Mismatch between the program and library build versions detected.
The library used 2.8 (no debug,ANSI,compiler with C++ ABI 1002,wx containers,compatible with 2.6),
and your program used 2.8 (no debug,ANSI,compiler with C++ ABI 1009,wx containers,compatible with 2.6).

I try doing ./runescape, perl runescape, and I even tried running rsu-query.
When trying to run rsu-query it gives me this:
Fatal Error: Mismatch between the program and library build versions detected.
The library used 2.8 (no debug,ANSI,compiler with C++ ABI 1002,wx containers,compatible with 2.6),
and your program used 2.8 (no debug,ANSI,compiler with C++ ABI 1009,wx containers,compatible with 2.6).
Aborted (core dumped).

Please help.
Thank you.

**Comment by HikariKnight** [comment]
according to wxwidgets that is an error you get if you have multiple versions of wxwidgets installed.

**Comment by GamingFTW** [comment]
Okay. I fixed the first error. Now I get this error. This was happening before. I get this error every single time I try to play. Permission Denied: http://pastebin.com/TegBDLmQ

**Comment by ivanpu** [comment]
Don't... Just *don't* launch it with `sudo`.

**Comment by ivanpu** [comment]
Looking more closely at the output:
Besides all the errors you are getting from running it as root, you also
don't have executable permission on
`/home/GamingFTW/Documents/rsu-client-master/runescape/rsu/bin/rsu-query-unix`.

**Comment by GamingFTW** [comment]
I fixed the error. I switched to Manjaro Linux.

**Comment by HikariKnight** [comment]
closed at request from Author
