### ISSUE TITLE
RS Linux thread forum link

### ISSUE THREAD

**Issue by ivanpu** [HikariKnight/rsu-client#91]
@HikariKnight
Since the thread is dead... should we remove the link from the client as well?

**Comment by HikariKnight** [comment]
Been working on moving the thread to the new forum. They decided to inform me about the removal of the old forum while i was on vacation and 1 day before the removal/hiding og the forum

**Comment by ivanpu** [comment]
Oh, good, I'll wait with PR then :)

**Comment by HikariKnight** [comment]
sadly it seems like they wont be sticking it

http://services.runescape.com/m=forum/forums.ws?409,410,414,65748539

that is the new link

**Comment by ivanpu** [comment]
:+1:
