### ISSUE TITLE
Launcher/client doesn't start

### ISSUE THREAD

**Issue by shinnova** [HikariKnight/rsu-client#93]
I have been trying all day to get the client to work but I haven't been succesful. I've tried multiple ways of installing but none of them seem to work for me. All dependencies are satisfied.
- Tried to install from the AUR with and without perl-wx. Had to use the 2.8 hack for perl-wx to get that installed, wxgtk3 doesn't work for me. 
- Tried a prebuilt version of the client.
- Used the x64 installer for linux provided here, also with and without perl-wx.
- Tried running it in fish and bash.
- As I am on an optimus laptop I've tried all of the above both with optirun and without. It did not make a difference.

No matter what way I tried installing the game, when trying to run it I would always get the same output:

```
ivanka@cute ~> runescape
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules

```

I do not get any more information than this, so I do not know what modules are missing, if any.

If you could help me with this that would be greatly appreciated, as I would love to use the client.

My system info if needed:

> ``````
>                    -`                      
>                   .o+`                    ivanka@cute
>                  `ooo/                    -----------
>                 `+oooo:                   OS: Arch Linux x86_64
>                `+oooooo:                  Kernel: 4.3.6-1-ck
>                -+oooooo+:                 Uptime: up 2 hours, 28 minutes
>              `/:-:++oooo+:                Packages: 870
>             `/++++/+++++++:               Shell: /usr/bin/fish
>            `/++++++++++++++:              Window Manager: SpectrWM
>           `/+++ooooooooooooo/`            Theme: Arc-Darker
>          ./ooosssso++osssssso+`           Font: Roboto 11
>         .oossssso-````/ossssss+`          Icons: AwOkenDark
>        -osssssso.      :ssssssso.         CPU: Intel Core i7-4700HQ @ 3.4GHz
>       :osssssss/        osssso+++.        GPU: Intel HD Graphics 4600
>      /ossssssss/        +ssssooo/-        GPU: Nvidia GeForce GTX 850M
>    `/ossssso+/:-        -:/+osssso+-      Memory: 6620MB / 7431MB
>   `+sso+:-`                 `.-/+oso:     Battery: 95%
>  `++:.                           `-/+/     
>  .`                                 `/                             
> ``````

**Comment by shinnova** [comment]
Just now I tried using the universal version as well, but the result was still the same.

**Comment by ivanpu** [comment]
>```
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
```

1. Is this the _whole_ output?
There should be more output, both in errorless run and when you encounter problems.
2. Except of `perl-wx`, do you have all the rest of the AUR package dependencies installed?

**Comment by shinnova** [comment]
```
ivanka@cute ~> runescape
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules

(rsu-query-unix:714): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(rsu-query-unix:714): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
```
Would be the whole output. I refrained from adding the Gtk-WARNING because I tend to get those in every application I start from the terminal, but I should have added it in case it does have anything to do with the client not starting. So I apologise for that.
Out of the dependencies I have all of the required ones, and from the optional dependencies I am only missing pulseaudio as I use alsa for my audio.

**Comment by shinnova** [comment]
I have fixed my gtk warning issue by installing gnome-themes-standard, and my full output is now
```
ivanka@cute ~> runescape
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
```
So it seems like this is not related like I originally thought.

**Comment by ivanpu** [comment]
Yes, that specific gtk warning should not interfere with the client, it'll only affect how the window is themed.

Actually, I've just remembered, that rsu-client does not pass some perl errors to the user... (@HikariKnight, is it intentional?)
What is the output of:
`$ perl -e "use Wx;"`

What else is worth checking, is perl related packages.
Do you have any local `perl-*` packages, that were built before the latest perl version bump?
If you do, then it's worth to rebuild them, and then try again.

**Comment by shinnova** [comment]
```
ivanka@cute ~> perl -e "use Wx;"
ivanka@cute ~> 
```
Seems I got nothing out of that. But I shall double check my perl packages. While I believe I managed to rebuild all of them today, I may have missed some.

**Comment by shinnova** [comment]
Made sure that my perl packages are all up to date now, but I'm afraid that once trying again I still get the exact same output. Is there maybe anything else I could try to get it running?

**Comment by ivanpu** [comment]
> Is there maybe anything else I could try to get it running?

I'm not familiar with perl, so let's ask @HikariKnight how to run the client with **all perl errors** displayed.

**Comment by shinnova** [comment]
With help from my partner I have more information when I try to run runescape, using perl -W. Now I receive the following as output:
``` 
ivanka@cute ~> runescape
Subroutine UNIVERSAL::VERSION redefined at /usr/share/perl5/core_perl/version.pm line 59.
Name "ExtUtils::MakeMaker::Locale::ENCODING_UTF-8" used only once: possible typo at /usr/share/perl5/core_perl/ExtUtils/MakeMaker/Locale.pm line 135.
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
Subroutine DynaLoader::dl_load_file redefined at /usr/lib/perl5/site_perl/Wx/Mini.pm line 74.
Subroutine DynaLoader::dl_load_file redefined at /usr/lib/perl5/site_perl/Wx/Mini.pm line 74.
Subroutine DynaLoader::dl_load_file redefined at /usr/lib/perl5/site_perl/Wx/Mini.pm line 74.
```
Hopefully this can be of use.

**Comment by shinnova** [comment]
After using perl -W on my partner's working install, it seems he gets the same output to start out with. So in the end it seems my last output may not have anything to do with the client not starting. Hopefully @HikariKnight can shed some light on the lack of perl errors.

**Comment by oleerik** [comment]
Looks like it somehow dies right before (what I get: ) 
```
The script is running from a system path!
/home/oleerik/.config/runescape will be used as client folder instead!
```

**Comment by fusion809** [comment]
I am getting the same error. I can run RSU on my old Lenovo E531 laptop running Arch Linux without issue. But on my newer HP ENVY 17 Notebook PC, I get the original error reported in this issue.

**Comment by fusion809** [comment]
Well I'll be, I installed some extra packages and now it launches fine. Not sure which one exactly led to the fix but the newly installed packages included:

* `java-environment`
* `poppler-glib`
* `webkitgtk2`

**Comment by HikariKnight** [comment]
@ivanpu @fusion809 @oleerik @shinnova 
other than the java environment package i have not seen the need for the other packages before.
also sorry for not noticing this before now

from what i see it fails to run this script and pass all parameters from rsu-query to it
https://github.com/HikariKnight/rsu-client/blob/master/runescape/rsu/bin/rsu-query-unix

can you try running "rsu-query client.launch.launcher" or run the rsu-query-unix with the same parameter and see what happens

**Comment by fusion809** [comment]
Something that is interesting though, even though RSU launches fine now, with the aforementioned packages installed, I am getting the same Java graphical glitch I mentioned in issue #92. I tried running `/opt/runescape/rsu/rsu-query client.launch.launcher` and it launched RSU without issue, but seeing how this issue is now resolved for me anyway, I don't think my results really matter anymore.

**Comment by Laodicean** [comment]
I had the same issue and installing `webkitgtk2` solved the problem for me. It's worth noting I already had `java-environment` and `poppler-glib` installed. I haven't run into anything like #92 yet though.
