### ISSUE TITLE
type `eb` is not known on line 57 in sourse

### ISSUE THREAD

**Issue by TheDarkDemon666** [HikariKnight/rsu-client#95]
@HikariKnight 

Hello I am new to liunx and i have ubuntu on a laptop and was a bit confused when the command didnt work

Hope you can help if you need any more info just ask and i will get i for you as fast as i can

**Comment by ivanpu** [comment]
Can you please be a bit more specific?
Or at least give the full console output to put the title into context?

**Comment by TheDarkDemon666** [comment]
![github problem](https://cloud.githubusercontent.com/assets/18311683/14334514/c4b626ce-fc4c-11e5-893b-e7a296596235.png)
@ivanpu

**Comment by ivanpu** [comment]
Looks like you have mistyped the `echo "deb ...` command... 
Run this:
```bash
sudo sed -i 's/^eb/deb/' /etc/apt/sources.list
sudo apt-get update && sudo apt-get install unix-runescape-client
```

**Comment by HostOnNet** [comment]
What is the content of  /etc/apt/sources.list ?

Paste result of command

```
cat  /etc/apt/sources.list
```
