### ISSUE TITLE
Void Repository

### ISSUE THREAD

**Issue by severustux** [HikariKnight/rsu-client#97]
Operating system : Ubuntu 16.04

Issue : The repository `http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu xenial Release` is empty

Description : When trying to install unix-runescape-client, after adding the repository as "`sudo apt-add-repository ppa:hikariknight/unix-runescape-client`", when tried to update, it gives: 

```
Err:9 http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu xenial/main amd64 Packages                                                              
  404  Not Found
Err:10 http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu xenial/main i386 Packages                                                               
  404  Not Found

```
```
W: The repository 'http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/hikariknight/unix-runescape-client/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by HikariKnight** [comment]
Forgot to upload 16.04 repo
Will do it when I get home

**Comment by ppihC** [comment]
Have you been home yet? ;) having the same problems

**Comment by HikariKnight** [comment]
Oh god I completely forgot this! Sorry but been dealing with hell IRL quite literally

**Comment by HikariKnight** [comment]
OK I have copied the packages of wily into the 2 newer releases and added it to the build recipes. So the ppa should have the files available in an hour or so, or you can visit the launchpad ppa page and download the debs now
