### ISSUE TITLE
Graphical Issue

### ISSUE THREAD

**Issue by Oliver-Buckler** [HikariKnight/rsu-client#99]
Update: The models start playing up when i check the Textures option in the graphical settings.

@HikariKnight 
Hi there, i'm having an issue with some of the models rendering.

Tested using OpenJDK and JRE, cleared cache and reinstalled the client. Currently running on a rMBP with Fedora 4.5.6.
Sadly i think it may be based more on my hardware if nobody else is having the issue.

Max graphics option
![rs](https://cloud.githubusercontent.com/assets/5634187/15986400/a6f40ba8-3039-11e6-9235-37ed47043f23.png)

Minimal graphics option
![rs2](https://cloud.githubusercontent.com/assets/5634187/15986401/aa3b1ed2-3039-11e6-8436-af0ffc3bff49.png)

Thanks.

**Comment by HostOnNet** [comment]
Which GPU you are using ? Since game client is provided by jagex, i don't think there is not much anyone can do about this. I am using Java client (switched back from NXT) and it work great for me. It may be your Graphics card or its driver.

**Comment by Oliver-Buckler** [comment]
@HostOnNet 
Yeah i see, i'm using integrated graphics. Just tested it with the java client too and the issue persisted, guess it is hardware related, thanks. Will mark as closed.
